CREATE SEQUENCE seq_category
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_brand
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_fuelType
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_motorisation
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_model
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_gear
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_users
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_model_gear
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_model_motor
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_model_fuel
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_car
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_announcement
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_sale
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_favorite
CREATE SEQUENCE seq_vente
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_favoris
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_fund
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_commission
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_profit
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_photo
   START WITH 1
   INCREMENT BY 1;

CREATE SEQUENCE seq_location
   START WITH 1
   INCREMENT BY 1;


CREATE SEQUENCE seq_origin
   START WITH 1
   INCREMENT BY 1;



CREATE SEQUENCE seq_announcement
   START WITH 1
   INCREMENT BY 1;
CREATE SEQUENCE seq_favorite
   START WITH 1
   INCREMENT BY 1;








